### ISSUE TITLE
关于 fork 项目 红龙贼

### ISSUE THREAD

**Issue by Steel-Shadow** [Moiezen/HS_SPR_CAL#14]
您好，近期我 fork 并修改了您的项目，开发了[红龙贼计算器](https://github.com/Steel-Shadow/HS-Alexstrasza-Rogue-Cal)。
最近考虑公开项目并向公众宣传，请问您是否同意呢？

目前项目修改还在进行中，还有诸多bug。

repo 地址：
https://github.com/Steel-Shadow/HS-Alexstrasza-Rogue-Cal

**Comment by Moiezen** [comment]
您好，可以的

2024-11-02 23:54:46 "Steel Shadow" ***@***.***> 写道：

您好，近期我 fork 并修改了您的项目，开发了红龙贼计算器。
最近考虑公开项目并向公众宣传，请问您是否同意呢？

目前项目修改还在进行中，还有诸多bug。

repo 地址：
https://github.com/Steel-Shadow/HS-Alexstrasza-Rogue-Cal
